require conf/machine/qemuarm.conf

# Use the same overrides as qemuarm machine.
MACHINEOVERRIDES:append = ":qemuarm"
WKS_FILE = "qemu.wks"
IMAGE_BOOT_FILES = "zImage"

# runqemu config
QB_DEFAULT_FSTYPE = "wic"
QB_FSINFO = "wic:no-kernel-in-fs"
QB_DEFAULT_BIOS = "${DEPLOY_DIR_IMAGE}/u-boot.bin"
QB_KERNEL_ROOT = "PARTLABEL=root"

do_image_wic[depends] += " \
    u-boot:do_deploy \
    "
