# From oe-core
require conf/machine/genericx86-64.conf

# We boot a Unified Kernel Image, so disable the separate kernel in runqemu
QB_KERNEL_ROOT  = ""
QB_DEFAULT_KERNEL = "none"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"

MACHINE_FEATURES:append = " efi"

MACHINEOVERRIDES:append = ":genericx86-64"

EFI_ARCH = "x64"

WIC_CREATE_EXTRA_ARGS:append = " \
--no-fstab-update \
"

# Final output formats
IMAGE_FSTYPES = "wic.gz"
WKS_FILE      = "zarhus-uki.wks"
