require conf/distro/include/zarhus-distro-common.conf

DISTRO = "zarhus-distro"
DISTRO_NAME = "Distro for Zarhus product"
DISTRO_FEATURES += "splash"
# imagemagick resize format
LOGO_SIZE="480!x640!"
APPEND += "quiet splash"
