# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zarhus"
BBFILE_PATTERN_zarhus = "^${LAYERDIR}/"
BBFILE_PRIORITY_zarhus = "10"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_zarhus = "1"

LAYERDEPENDS_zarhus = " \
    core \
    openembedded-layer \
    "

LAYERSERIES_COMPAT_zarhus = "scarthgap master"

# Use Rust recipes from Zarhus, because Zarhus has newer versions than other
# layers on scarthgap release:
PREFERRED_PROVIDER_rust = "zarhus-distro"
PREFERRED_PROVIDER_rust-native = "zarhus-distro"
PREFERRED_PROVIDER_cargo = "zarhus-distro"
PREFERRED_PROVIDER_cargo-native = "zarhus-distro"
PREFERRED_PROVIDER_cargo-c-native = "zarhus-distro"
PREFERRED_PROVIDER_libstd-rs = "zarhus-distro"
PREFERRED_PROVIDER_rust-cross-canadian = "zarhus-distro"
PREFERRED_PROVIDER_rust-llvm = "zarhus-distro"
PREFERRED_PROVIDER_rust-llvm-native = "zarhus-distro"
PREFERRED_VERSION_rust = "1.83.0"
PREFERRED_VERSION_rust-native = "1.83.0"
PREFERRED_VERSION_cargo = "1.83.0"
PREFERRED_VERSION_cargo-native = "1.83.0"
PREFERRED_VERSION_cargo-c-native = "0.9.30+cargo-0.77.0"
PREFERRED_VERSION_libstd-rs = "1.83.0"
PREFERRED_VERSION_rust-cross-canadian = "1.83.0"
PREFERRED_VERSION_rust-llvm = "1.83.0"
PREFERRED_VERSION_rust-llvm-native = "1.83.0"
