verify_locked() {
    local user="$1"
    if [ "$(passwd -S "$user" | cut -f 2 -d " ")" = "L" ]; then
        return 0
    fi
    return 1
}

section "hardening.conf" red
section "Users"
cukinia_user user
cukinia_user_memberof user user sudo
as "Check if root account is locked" cukinia_cmd verify_locked root

section "Kernel lockdown feature"
as "Check if access to /dev/mem is restricted" not cukinia_cmd dd if=/dev/mem
dmesg_log=$(mktemp)
dmesg > "$dmesg_log"
as "Check if kernel lockdown is enabled" cukinia_cmd grep "Kernel is locked down from Kernel configuration" "$dmesg_log"
as "Check dmesg for blocked access to /dev/mem" cukinia_cmd grep "Lockdown:.*/dev/mem,kmem,port is restricted" "$dmesg_log"
