# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-uki"
BBFILE_PATTERN_otab-uki = "^${LAYERDIR}/"
# One higher than meta-swupdate
BBFILE_PRIORITY_otab-uki = "7"

BBFILES_DYNAMIC += " \
    zarhus-bsp-x86_64:${LAYERDIR}/dynamic-layers/zarhus-bsp-x86_64/recipes-*/*/*.bbappend \
    zarhus:${LAYERDIR}/dynamic-layers/zarhus-distro/recipes-*/*/*.bb* \
    zarhus-encryption:${LAYERDIR}/dynamic-layers/zarhus-encryption/recipes-*/*/*.bb* \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-uki = "1"

LAYERDEPENDS_otab-uki = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    readonly-rootfs-overlay \
    "

LAYERSERIES_COMPAT_otab-uki = "scarthgap master"

IMAGE_INSTALL:append = " fw-printenv"

##################################################
# OTAB variables
##################################################

WKS_FILE:x86-64 = "otab-uki-x86-uefi.wks.in"
OTAB_LABEL_BOOT_A ??= "boot_a"
OTAB_LABEL_BOOT_B ??= "boot_b"
OTAB_LABEL_ROOTFS_A ??= "rootfs_a"
OTAB_LABEL_ROOTFS_B ??= "rootfs_b"
OTAB_LABEL_ROOTFS_OVERLAY ??= "rwoverlay"
OTAB_LABEL_DATA ??= "data"

##################################################
# WKS rootfs-sed plugin variables
##################################################

# Generated with 'uuid -m' tool. Check
# dynamic-layers/zarhus-bsp-x86_64/recipes-zarhus/images/otab-uki.inc to see how
# to generate UUID based on repository commit
BOOT_A_UUID ??= "7d44af0e"
BOOT_B_UUID ??= "b32e6740"
ROOT_A_UUID ??= "b8a30442-412f-11f0-a7c2-d795d2926e45"
ROOT_B_UUID ??= "be43152c-412f-11f0-a99a-17f6567575ce"

# Temporary labels/uuid used during update
BOOT_TMP_UUID = "AAAA1111"
ROOT_TMP_UUID = "11111111-1111-1111-1111-111111111111"
BOOT_TMP_LABEL = "TMP_BOOT"
ROOT_TMP_LABEL = "TMP_ROOT"

WICVARS:append = " \
    BOOT_A_UUID ROOT_A_UUID \
"

UKI_CMDLINE:append = " \
    rootrw=/dev/disk/by-label/${OTAB_LABEL_ROOTFS_OVERLAY} \
    "

OTAB_BOOT_A_IMAGE_FSTYPE = ".direct.p1.gz"
OTAB_ROOTFS_A_IMAGE_FSTYPE ??= ".direct.p2.gz"
OTAB_DEVICE_BOOT_A ??= "${OTAB_DEVICE_MAIN}p1"
OTAB_DEVICE_BOOT_B ??= "${OTAB_DEVICE_MAIN}p3"
