# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zarhus-bsp-qemuarm"
BBFILE_PATTERN_zarhus-bsp-qemuarm = "^${LAYERDIR}/"
BBFILE_PRIORITY_zarhus-bsp-qemuarm = "6"

LAYERDEPENDS_zarhus-bsp-qemuarm = "core"
LAYERSERIES_COMPAT_zarhus-bsp-qemuarm = "scarthgap"
