# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zarhus-encryption"
BBFILE_PATTERN_zarhus-encryption = "^${LAYERDIR}/"
BBFILE_PRIORITY_zarhus-encryption = "1"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_zarhus-encryption = "1"

LAYERDEPENDS_zarhus-encryption = " \
    core \
    openembedded-layer \
    "

LAYERSERIES_COMPAT_zarhus-encryption = "scarthgap master"
