#!/bin/bash

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS] COMMAND

Track and analyze heap usage to detect memory leaks
Arguments:
COMMAND    Command to run

Options:
-h, --help Print this help and exit
EOF
}

parse_params() {
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
    -h | --help) usage && exit ;;
    -?*) usage && exit 1 ;;
    *)
      if [ -z "$COMMAND" ]; then
          COMMAND="$1"
      else
          echo "Unexpected argument: $1"
          usage
          exit 1
      fi
      ;;
    esac
    shift
  done
  IFS=' ' read -r -a CMD_ARRAY <<< "$COMMAND"
}

parse_params "$@"
echo "Analyzing heap usage."
heaptrack "${CMD_ARRAY[@]}"
