BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zarhus-bsp-x86_64"
BBFILE_PATTERN_zarhus-bsp-x86_64 = "^${LAYERDIR}/"
LAYERSERIES_COMPAT_zarhus-bsp-x86_64 = "scarthgap"
