#!/bin/sh

wait_for_enter() {
    echo "Press Enter to continue..."
    read -r _ignore
}

error_check() {
    ret=$?
    err_msg="$1"
    if [ $ret != 0 ]; then
        fatal "$err_msg (err=$ret)"
    fi
}

# shellcheck disable=3045
ask_for_password() {
    _password=
    _password2=
    # Questions are outputted on stderr, password is echoed on stdout
    i=1
    while [ "${i}" -le 3 ]; do
        read -srp "Enter disk encryption password: " _password >&2
        echo "" >&2
        read -srp "Verify password: " _password2 >&2
        echo "" >&2
        if [ "${_password}" != "${_password2}" ]; then
            echo "Passwords are not the same!" >&2
            i=$((i+1))
            continue
        fi
        echo "" >&2
        printf '%s' "${_password}"
        return 0
    done
    return 1
}

# shellcheck disable=3045
ask_for_password_no_verify() {
    _password=
    read -srp "Enter disk encryption password: " _password >&2
    echo "" >&2
    printf '%s' "${_password}"
}

# encrypt_device <device> [flags]
# generates new recovery password if encrypting for the first time, otherwise
# enrolls previous recovery key. flags can be set to no_reencrypt to encrypt
# device without in-place re-encryption. It's faster but overwrites whole
# filesystem
encrypt_device() {
    device_to_encrypt="$1"
    if [ "$2" = "no_reencrypt" ]; then
        reencrypt=
    else
        reencrypt="y"
    fi
    password="$3"

    luks_label="luks_$(get_partition_partlabel "$device_to_encrypt")"
    # shellcheck disable=SC3040
    set -o pipefail

    echo "Preparing to encrypt $device_to_encrypt"
    umount "$device_to_encrypt" 2>/dev/null
    if [ -n "$reencrypt" ]; then
        device_size="$(lsblk -nbo SIZE "$device_to_encrypt")"
        e2fsck -fp "$device_to_encrypt" >/dev/null
        # reduce fs size to make space for LUKS2 header
        resize2fs "$device_to_encrypt" "$(($device_size/1024/1024-32))M" -f >/dev/null 2>&1
        error_check "Failed to shrink filesystem"
    fi
    echo "Encrypting $device_to_encrypt"
    if [ -n "$reencrypt" ]; then
        printf '%s' "$password" | cryptsetup reencrypt --force-password \
            --encrypt --type luks2 --reduce-device-size 32M "$device_to_encrypt" 2>/dev/null
    else
        printf '%s' "$password" | cryptsetup luksFormat --batch-mode --force-password \
            --type luks2 "$device_to_encrypt"
    fi
    error_check "Encryption failed"
    cryptsetup config "$device_to_encrypt" --label "$luks_label"

    printf '%s' "$password" | cryptsetup open "$device_to_encrypt" "$luks_label"
    error_check "Couldn't decrypt $device_to_encrypt"
    if [ -n "$reencrypt" ]; then
        echo "n" | e2fsck -f -p "/dev/mapper/$luks_label" >/dev/null
        resize2fs "/dev/mapper/$luks_label" >/dev/null 2>&1
    fi
    echo "Successfully encrypted $device_to_encrypt"

    # shellcheck disable=SC3040
    set +o pipefail
}

parse_bootparam_to_device() {
    param="$1"
    # Either PARTLABEL, PARTUUID or path to device
    if [ "$(echo "${param}" | cut -c1-9)" = "PARTUUID=" ]; then
        partuuid=$(echo "$param" | cut -c10-)
        param="/dev/disk/by-partuuid/$partuuid"
    elif [ "$(echo "${param}" | cut -c1-10)" = "PARTLABEL=" ]; then
        partlabel=$(echo "$param" | cut -c11-)
        param="/dev/disk/by-partlabel/$partlabel"
    fi
    echo "$param"
    if [ ! -b "$param" ]; then
        return 1
    fi
    return 0
}

get_partition_partlabel() {
    lsblk -no PARTLABEL "$1" | awk NF
}

encrypt_decrypt_enabled() {
	return 0
}

# Function uses 2 arguments.
# - rd.luks.rootfs=<PARTITION>
# - rd.luks.encrypt=<PARTITION>[,PARTITION]...
# where <PARTITION> can be either:
# - PARTLABEL=<PARTLABEL>
# - PARTUUID=<PARTUUID>
# - path to block device e.g. /dev/sda2
# Script first checks if rootfs is encrypted. If it isn't then it encrypts
# partitions in rd.luks.encrypt after that it encrypts rd.luks.rootfs.
# If rootfs is encrypted then it first decrypts rootfs and then all partitions
# in rd.luks.encrypt. Initramfs will try to continue booting even if partitions
# in rd.luks.encrypt couldn't be decrypted
encrypt_decrypt_run() {
    if [ -z "$bootparam_rd_luks_rootfs" ]; then
        return 0;
    fi

    rd_luks_rootfs="$(parse_bootparam_to_device "$bootparam_rd_luks_rootfs")"
    error_check "$rd_luks_rootfs doesn't exist or isn't block device"
    rootfs_luks_label="luks_$(get_partition_partlabel "$rd_luks_rootfs")"

    # if rootfs is already encrypted then only decrypt
    if cryptsetup isLuks "$rd_luks_rootfs" >/dev/null; then
        password=
        if ! cryptsetup open --token-only "$rd_luks_rootfs" "$rootfs_luks_label" 2>/dev/null; then
            i=1
            while true; do
                password="$(ask_for_password_no_verify)"
                if printf '%s' "$password" | cryptsetup open "$rd_luks_rootfs" "$rootfs_luks_label" 2>/dev/null; then
                    break
                elif [ "$i" -le 3 ]; then
                    echo "Failed to decrypt $rd_luks_rootfs, try again"
                else
                    fatal "Failed to decrypt $rd_luks_rootfs!"
                fi
                i=$((i+1))
            done
        fi
        error_check "Couldn't decrypt $rd_luks_rootfs"

        # shellcheck disable=SC2154
        for decrypt in $(echo "$bootparam_rd_luks_encrypt" | tr ',' '\n'); do
            decrypt_part="$(echo "$decrypt" | cut -d'=' -f 1,2)"
            if ! decrypt_device=$(parse_bootparam_to_device "$decrypt_part"); then
                echo "$decrypt_device doesn't exist or isn't block device"
                continue
            fi
            luks_label="luks_$(get_partition_partlabel "$decrypt_device")"
            # skip already opened rootfs
            if [ "$rootfs_luks_label" = "$luks_label" ]; then
                continue
            fi
            if ! printf '%s' "$password" | cryptsetup open "$decrypt_device" "$luks_label" 2>/dev/null; then
                echo "Couldn't decrypt $decrypt_device"
            fi
        done
        return 0
    fi

    # Encrypt - should get here only once, during first boot.
    password="$(ask_for_password)"
    error_check "Failed to enter the same password multiple times"
    for encrypt in $(echo "$bootparam_rd_luks_encrypt" | tr ',' '\n'); do
        encrypt_part="$(echo "$encrypt" | cut -d'=' -f 1,2)"
        encrypt_flag="$(echo "$encrypt" | cut -d'=' -f 3)"
        encrypt_device=$(parse_bootparam_to_device "$encrypt_part")
        error_check "$encrypt_device doesn't exist or isn't block device"
        luks_label="luks_$(get_partition_partlabel "$encrypt_device")"
        # Let's encrypt rootfs at the end
        if [ "$rootfs_luks_label" = "$luks_label" ]; then
            continue
        fi
        encrypt_device "$encrypt_device" "$encrypt_flag" "$password"
        error_check "Couldn't encrypt $encrypt_device."
    done
    encrypt_device "$rd_luks_rootfs" "" "$password"
    error_check "Couldn't encrypt $rd_luks_rootfs."
}
