section()
{
    local text=$1
    local color=${2:-yellow}
	cukinia_log "$(_colorize "$color" "----> $text <----")"
}

cukinia_conf_include /etc/cukinia/conf.d/*.conf
cukinia_log "result: $cukinia_failures failure(s)"
