verify_locked() {
    local user="$1"
    if [ "$(passwd -S "$user" | cut -f 2 -d " ")" = "L" ]; then
        return 0
    fi
    return 1
}

section "distro.conf" red
section "Users"
cukinia_user user
cukinia_user_memberof user user sudo
as "Check if root account is locked" cukinia_cmd verify_locked root
