# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-common"
BBFILE_PATTERN_otab-common = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-common = "5"
BBFILES_DYNAMIC += " \
    zarhus:${LAYERDIR}/dynamic-layers/zarhus-distro/recipes-*/*/*.bbappend \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-common = "1"

LAYERDEPENDS_otab-common = " \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-common = "scarthgap master"

BOOT_LABEL = "${OTAB_LABEL_BOOT_A}"
ROOTFS_LABEL = "${OTAB_LABEL_ROOTFS_A}"

##################################################
# OTAB variables
##################################################
OTAB_ROOTFS_IMAGE_NAME ??= "core-image-minimal"
OTAB_ROOTFS_IMAGE_FSTYPE ??= ".direct.p2.gz"
OTAB_ROOTFS_A_IMAGE_FSTYPE ??= "${OTAB_ROOTFS_IMAGE_FSTYPE}"

# OTAB uses labels during update to locate appropriate partition for writing.
# By default this is /dev/disk/by-label which is ok in most cases. This variable
# may be altered to /dev/mapper for platforms that access rootfs through Device
# Mapper.
OTAB_ROOTFS_SEARCH_PATH ??= "/dev/disk/by-label"
OTAB_STORAGE_DEVICE ??= "mmc"

OTAB_DEVICE_MAIN ??= "/dev/mmcblk0"
OTAB_DEVICE_BOOT ??= "${OTAB_DEVICE_MAIN}p1"
OTAB_DEVICE_BOOT_A ??= "${OTAB_DEVICE_BOOT}"
OTAB_DEVICE_BOOT_B ??= "${OTAB_DEVICE_BOOT}"
OTAB_BOOT_A_IMAGE_FSTYPE ??= ".direct.p1.gz"
OTAB_DEVICE_ROOTFS_A ??= "${OTAB_DEVICE_MAIN}p2"
OTAB_DEVICE_ROOTFS_B ??= "${OTAB_DEVICE_MAIN}p4"
OTAB_DEVICE_ROOTFS_OVERLAY ??= "${OTAB_DEVICE_MAIN}p5"
OTAB_DEVICE_DATA ??= "${OTAB_DEVICE_MAIN}p6"

OTAB_LABEL_BOOT ??= "boot"
OTAB_LABEL_BOOT_A ??= "${OTAB_LABEL_BOOT}"
OTAB_LABEL_BOOT_B ??= "${OTAB_LABEL_BOOT}"
OTAB_LABEL_ROOTFS_A ??= "rootfsa"
OTAB_LABEL_ROOTFS_B ??= "rootfsb"
OTAB_LABEL_ROOTFS_OVERLAY ??= "rwoverlay"
OTAB_LABEL_DATA ??= "data"

OTAB_BOOT_PART_SIZE ??= "128"
OTAB_ROOTFS_PART_SIZE ??= "512"
OTAB_ROOTFS_OVERLAY_PART_SIZE ??= "512"
OTAB_DATA_PART_SIZE ??= "4096"

OTAB_KERNEL_IMAGE_TYPE ??= "bzImage-initramfs"
OTAB_KERNEL_IMAGE_EXTENSION ??= ".bin"

OTAB_KERNEL_IMAGE_A ??= "${OTAB_KERNEL_IMAGE_TYPE}-a"
OTAB_KERNEL_IMAGE_B ??= "${OTAB_KERNEL_IMAGE_TYPE}-b"

OTAB_SELECTION_A ??= "2"
OTAB_SELECTION_B ??= "3"

OTAB_WIC_ROOTFS_EXTRA_ARGS ??= ""

OTAB_INITRAMFS_IMAGE ??= "rorootfs-overlay-initramfs"

IMAGE_INSTALL:append = " \
    swupdate \
    otab \
"

OTAB_ROOT_PREFIX ??= "/"
OTAB_BOOT_DIR_REL ??= "boot"
OTAB_BOOT_DIR ??= "${OTAB_ROOT_PREFIX}${OTAB_BOOT_DIR_REL}"
OTAB_DATA_DIR_REL ??= "data"
OTAB_DATA_DIR ??= "${OTAB_ROOT_PREFIX}${OTAB_DATA_DIR_REL}"

# those paths should not be part of the rootfs partition
OTAB_ROOTFS_EXCLUDE_ARGS ??= " \
    --exclude-path ${OTAB_DATA_DIR_REL}/ \
                   ${OTAB_BOOT_DIR_REL}/ \
"

OTAB_WIC_ROOTFS_EXTRA_ARGS ??= "${OTAB_ROOTFS_EXCLUDE_ARGS}"

OTAB_SIGNED ??= "false"
OTAB_ENCRYPTED ??= "false"
OTAB_RESET_OVERLAY ??= "false"

IMAGE_FSTYPES = "wic.gz wic.bmap"

# rpi-config
RPI_USE_U_BOOT:rpi = "1"
KERNEL_BOOTCMD:rpi = "bootz"

# pass extra args to wic
# * to prevent wic from updating /etc/fstab file
WIC_CREATE_EXTRA_ARGS:append = "\
    --no-fstab-update \
    "

# initramfs
INITRAMFS_IMAGE = "${OTAB_INITRAMFS_IMAGE}"
INITRAMFS_IMAGE_BUNDLE = "1"

OTAB_UPDATE_SLOT_START ??= "00:00:00"
OTAB_UPDATE_SLOT_STOP ??= "23:59:59"
OTAB_UPDATE_DAYS ??= "1"
OTAB_UPDATE_POLL_INTERVAL ??= "15"
OTAB_UPDATE_POLL_MAX ??= "15"
OTAB_TIME_SLOT_CHECK_INTERVAL ??= "1"
