check_tpm_keyslots() {
    luks_dump="$1"
    jq_arg='
    {
        tpm_keyslots: [.tokens[] | select(.type == "systemd-tpm2") | .keyslots[]],
        all_keyslots: [.keyslots | keys[] | tonumber]
    } | select(((.all_keyslots | length) - (.tpm_keyslots | length)) != 0) | error("Not all keyslots use TPM2")
    '
    echo "$luks_dump" | jq "$jq_arg"
}

if as "Check if rootfs is encrypted" cukinia_cmd cryptsetup status "$(df / --output=source | tail -1)";
then
    encrypted_device=$(cryptsetup status "$(df / --output=source | tail -1)" | sed -n "s|.*device:.*\(/dev/.*\)|\1|p")
    luks_dump=$(cryptsetup luksDump "$encrypted_device" --dump-json-metadata 2>/dev/null)
    ret=$?
    as "Check if we can get rootfs LUKS device information dump" cukinia_test $ret -eq 0
    as "Check if rootfs can only be decrypted with TPM2" cukinia_cmd check_tpm_keyslots "$luks_dump"
fi
